name: Manually publish documentation

on:
  workflow_dispatch:
    inputs:
      sphinxDocVersionManual:
        description: "Version to set for documentation"
        required: true
        type: string

jobs:
  build_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build docs
        env:
          SPHINX_DOC_VERSION_MANUAL: ${{ inputs.sphinxDocVersionManual }}
        run: tox -e docs

      - name: Add nojekyll file
        run: touch ./docs/_build/html/.nojekyll

      - name: GH Pages Deployment
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./docs/_build/html
          clean: true # Automatically remove deleted files from the deploy branch
